apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: 17
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: ruby    
  serviceClaims:
   - name: db
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: mysql-spring
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 512Mi
  source:
    git:
      # update when code is pushed to a new location
      url: https://github.com/trevorputbrese/spring-sensors
      ref:
        branch: main
